version: "3"
services:
  app:
    build:
      context: .
    command:
      # =========本番===========
      bundle exec puma -C config/puma.rb -e production
      # ========ローカル==========
      # bundle exec puma -C config/puma.rb
      # ========================

    volumes:
      - .:/team-plz
      - public-data:/team-plz/public
      - tmp-data:/team-plz/tmp
      - log-data:/team-plz/log
    networks:
      - team-plz-network

    # ===========本番コメントアウト=============
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: team_plz_development
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - team-plz-network
  # ======================================

  web:
    # =======for pry-rails=======
    stdin_open: true
    tty: true
    # ===========================
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/team-plz/public
      - tmp-data:/team-plz/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - team-plz-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  team-plz-network:
    external: true
