version: '3'
services:
    app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/team-plz
ports:
      - 80:80
    depends_on:
      - app
    networks:
      - team-plz-network
web:
    build:
      context: ./nginx_docker
    cports:
      - 80:80
    depends_on:
      - app
    networks:
      - team-plz-network